// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMhmoCNClPL0K7XofjzPX0lV4oby3c16I',
    appId: '1:930381187024:web:2a0a3cece38e5c98519bd5',
    messagingSenderId: '930381187024',
    projectId: 'newappoinment',
    authDomain: 'newappoinment.firebaseapp.com',
    storageBucket: 'newappoinment.firebasestorage.app',
    measurementId: 'G-TSNHLH528Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPZlLfvcC4F40pu7s5LIi3i-Rqegn3Z3g',
    appId: '1:930381187024:android:1453a1803a5f5122519bd5',
    messagingSenderId: '930381187024',
    projectId: 'newappoinment',
    storageBucket: 'newappoinment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFqOww03_h83dIMS4ygyyBxtr0-2bTXl0',
    appId: '1:930381187024:ios:9a58aa6cdd2b3f08519bd5',
    messagingSenderId: '930381187024',
    projectId: 'newappoinment',
    storageBucket: 'newappoinment.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFqOww03_h83dIMS4ygyyBxtr0-2bTXl0',
    appId: '1:930381187024:ios:9a58aa6cdd2b3f08519bd5',
    messagingSenderId: '930381187024',
    projectId: 'newappoinment',
    storageBucket: 'newappoinment.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMhmoCNClPL0K7XofjzPX0lV4oby3c16I',
    appId: '1:930381187024:web:d75e5fbe01c06e14519bd5',
    messagingSenderId: '930381187024',
    projectId: 'newappoinment',
    authDomain: 'newappoinment.firebaseapp.com',
    storageBucket: 'newappoinment.firebasestorage.app',
    measurementId: 'G-44RTVP0K09',
  );
}
